import time

print("You open your computer and see this on the screen......")
time.sleep(3)
HACK = input("DELETE CORE MEMORY ? y/n")
if HACK == ("y"):
      print("LOADING...")
      time.sleep(3)
      print ("DONE!")
      print("CORE MEMORY WAS DELETED!")
elif HACK == ("n"):
       SURE = input("ARE YOU SURE ? y/n")
       SURE = ("y")
       print("LOADING...")
       time.sleep(3)
       print ("DONE!")
       print("CORE MEMORY WAS DELETED!")
elif SURE == ("n"):
       print("LOADING...")
       time.sleep(3)
       print ("DONE!")
       print("CORE MEMORY WAS DELETED!")
NAME = input("Insert your name")
print("Hello user " + NAME + " !")
time.sleep(2)
print("ALERT!")
time.sleep(1)
print("MAIN ACCOUNT IN USE.")
HACK2 = input("MAIN ACCOUNT IN RISK! (main account has a risk of being hacked) START DEFCON VIRUS ALERT ? y/n")
if HACK2 == ("y"):
    print(" INITALIZING DEFCON PROTOCOL")
elif HACK2 == ("n"):
    print("DEFCON PROTOCOL DEACTIVATED...")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("AlegY?")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    print("ALERT!")
    time.sleep(7)
    print("H@cKI5g A8c0Un7...")
    time.sleep(2)
print("VIRUS WAS FOUND AND DESTROYED")
time.sleep(4)
print("User " + NAME + " you have one email on your inbox")
time.sleep(2)
print("Opening inbox..")
time.sleep(3)
print("Opening email : openme. from: anonymous")
time.sleep(5)
print("Nothing to see here....")
time.sleep(1)
print(NAME +": this seems suspicious...")
time.sleep(5)
print("New email... Opening new email")
time.sleep(3)
EGG = input ("For an easter egg insert the code or type n")
if EGG == ("AlegY?"):
    print("Some say that this will not matter for the story of truth...")
    print("TRANSFERING $1,000,000,000,000,000,000,000,000,000 to " + NAME + "´s bank account...")
elif EGG == ("n"):
    print("YOU FAILED TO ACHIVE THE EASTER EGG YOU LITTLE CREATURE!")
print("  Deleting email.")
time.sleep(2)
print("Quiting inbox...")
time.sleep(3)
print("Plugin in USB STICK: Disk X) 100% full / max 110 terabytes...")
time.sleep(7)
print("Runing AI.kba...")
time.sleep(5)
print("Greetings " + NAME +" I am your personal AI(artificial intellingence) assistant")
time.sleep(5)
print("I am gooing to open the KE archive...")
print("Opening...")
time.sleep(5)
print("EXECUTING...")
time.sleep(5)

